#!/usr/bin/env ruby
# frozen_string_literal: true

$LOAD_PATH.unshift(File.expand_path("../lib", __dir__)) unless $LOAD_PATH.include?(File.expand_path("../lib", __dir__))
require "drakon_ruby"

path = ARGV[0]
abort "usage: drakon2rb <file.drakon>" unless path && File.file?(path)

source = File.read(path, encoding: "UTF-8")
puts DrakonRuby::Translator.new(source).to_ruby
